---
- name: install confd files
  include_role:
    name: confd-files-1.0.5

- name: install jdk
  include_role:
    name: install-1.0.5
  vars:
    opts:
      pkg_name: jdk
      pkg_version: "{{ java_pkg.version }}"
      pkg_type: tgz
      pkg_url: "{{ java_pkg.url }}"
      extracts: yes
      creates: bin/javac
      bin_path: bin
  loop: "{{ java_pkgs }}"
  loop_control:
    loop_var: java_pkg

- name: link java version
  file:
    src: "{{ java_pkg.version }}"
    dest: /opt/jdk/{{ java_pkg.version | regex_search("^[0-9]+") }}
    state: link
  loop: "{{ java_pkgs }}"
  loop_control:
    loop_var: java_pkg

- name: create service user
  include_role:
    name: create-service-user-1.0.0
  vars:
    svc_user: tomcat

- name: install tomcat packages
  include_role:
    name: install-1.0.5
  vars:
    opts:
      pkg_name: tomcat
      pkg_version: "{{ tomcat_version }}"
      pkg_url: https://mirrors.tuna.tsinghua.edu.cn/apache/tomcat/tomcat-{{ tomcat_version | regex_search('^[0-9]+') }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
      pkg_type: tgz
      extracts: yes
      target_owner: tomcat
      target_group: svc
      creates: bin
  loop: "{{ tomcat_versions }}"
  loop_control:
    loop_var: tomcat_version

- name: link tomcat version
  file:
    src: "{{ tomcat_version }}"
    dest: /opt/tomcat/{{ tomcat_version | regex_search("^[0-9]+") }}
    state: link
  loop: "{{ tomcat_versions }}"
  loop_control:
    loop_var: tomcat_version

- name: install app files
  copy:
    src: "{{ role_path }}/files/{{ dir_path }}"
    dest: /{{ dir_path }}
    owner: root
    group: svc
    mode: preserve
  loop:
  - opt/app/
  loop_control:
    loop_var: dir_path

- name: increase inode watch limit
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
