---
- hosts: all
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  vars_files:
    - /root/.qcacode
  roles:
  - update-apt-sources-1.0.0
  - disable-apt-jobs-1.0.0
  - disable-motd-1.0.0
  - app-agent-1.0.6
  - appctl-1.1.4
  - arping-1.0.5
  - jq-1.0.9
  - caddy-1.1.5
  - tomcat
